version: '2'
services:
  redis:
    container_name: redis
    image: redis:5.0.5-alpine
    ports:
      -  "6379:6379"
    volumes:
      - /data/etc/redis/redis.conf:/etc/redis/redis.conf:rw
      - /data/db/redis/data:/data:rw
    restart: unless-stopped
  mysql:
    container_name: mysql
    image: mysql:8.0.25
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - /data/db/mysql:/var/lib/mysql:rw
    restart: unless-stopped


