server:
  debug: true
  port: 3000
  pprof: true

database:
  wei:
    user: root
    pwd: root
    host: localhost
    port: 3306
    dbname: wei
    charset: utf8mb4
    parse_time: True
    location: Local
    max_idle_cons: 2
    max_open_cons: 20
    conn_max_lifetime_minutes: 200

logger:
  filename: "./logs/admin.log"
  max_size: 5
  max_backups: 7
  max_age: 14
  compress: true
  level: -1 # debug=-1, info=0, warn=1
  json: false