// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: admin_account.proto

package admin_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 登录
type ReqLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty" binding:"required,adminname" label:"用户名"` // 用户名 @gotags: binding:"required,adminname" label:"用户名"
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty" binding:"required,adminpwd" label:"密码"` // 密码  @gotags: binding:"required,adminpwd" label:"密码"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqLogin) Reset() {
	*x = ReqLogin{}
	mi := &file_admin_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqLogin) ProtoMessage() {}

func (x *ReqLogin) ProtoReflect() protoreflect.Message {
	mi := &file_admin_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqLogin.ProtoReflect.Descriptor instead.
func (*ReqLogin) Descriptor() ([]byte, []int) {
	return file_admin_account_proto_rawDescGZIP(), []int{0}
}

func (x *ReqLogin) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ReqLogin) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RespLoginData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *AdminInfo             `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespLoginData) Reset() {
	*x = RespLoginData{}
	mi := &file_admin_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespLoginData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespLoginData) ProtoMessage() {}

func (x *RespLoginData) ProtoReflect() protoreflect.Message {
	mi := &file_admin_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespLoginData.ProtoReflect.Descriptor instead.
func (*RespLoginData) Descriptor() ([]byte, []int) {
	return file_admin_account_proto_rawDescGZIP(), []int{1}
}

func (x *RespLoginData) GetData() *AdminInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

// 账号详情
type ReqAccountInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  bool                   `protobuf:"varint,1,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"` //刷新token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqAccountInfo) Reset() {
	*x = ReqAccountInfo{}
	mi := &file_admin_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqAccountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqAccountInfo) ProtoMessage() {}

func (x *ReqAccountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_admin_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqAccountInfo.ProtoReflect.Descriptor instead.
func (*ReqAccountInfo) Descriptor() ([]byte, []int) {
	return file_admin_account_proto_rawDescGZIP(), []int{2}
}

func (x *ReqAccountInfo) GetRefreshToken() bool {
	if x != nil {
		return x.RefreshToken
	}
	return false
}

type RespAccountInfoData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *AdminInfo             `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespAccountInfoData) Reset() {
	*x = RespAccountInfoData{}
	mi := &file_admin_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespAccountInfoData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespAccountInfoData) ProtoMessage() {}

func (x *RespAccountInfoData) ProtoReflect() protoreflect.Message {
	mi := &file_admin_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespAccountInfoData.ProtoReflect.Descriptor instead.
func (*RespAccountInfoData) Descriptor() ([]byte, []int) {
	return file_admin_account_proto_rawDescGZIP(), []int{3}
}

func (x *RespAccountInfoData) GetData() *AdminInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

// 账号编辑
type ReqAccountEdit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty" binding:"required,min=1,max=32" label:"用户名"` //名称 @gotags:  binding:"required,min=1,max=32" label:"用户名"
	Avatar        string                 `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty" binding:"url" label:"头像地址"`     //头像 @gotags:  binding:"url" label:"头像地址"
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty" binding:"email" label:"邮箱"`       //邮箱 @gotags:  binding:"email" label:"邮箱"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqAccountEdit) Reset() {
	*x = ReqAccountEdit{}
	mi := &file_admin_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqAccountEdit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqAccountEdit) ProtoMessage() {}

func (x *ReqAccountEdit) ProtoReflect() protoreflect.Message {
	mi := &file_admin_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqAccountEdit.ProtoReflect.Descriptor instead.
func (*ReqAccountEdit) Descriptor() ([]byte, []int) {
	return file_admin_account_proto_rawDescGZIP(), []int{4}
}

func (x *ReqAccountEdit) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ReqAccountEdit) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *ReqAccountEdit) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type RespAccountEditData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespAccountEditData) Reset() {
	*x = RespAccountEditData{}
	mi := &file_admin_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespAccountEditData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespAccountEditData) ProtoMessage() {}

func (x *RespAccountEditData) ProtoReflect() protoreflect.Message {
	mi := &file_admin_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespAccountEditData.ProtoReflect.Descriptor instead.
func (*RespAccountEditData) Descriptor() ([]byte, []int) {
	return file_admin_account_proto_rawDescGZIP(), []int{5}
}

// 修改密码
type ReqAccountPasswordEdit struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OldPassword     string                 `protobuf:"bytes,1,opt,name=oldPassword,proto3" json:"oldPassword,omitempty" binding:"required,adminpwd" label:"旧密码"`         //旧密码 @gotags:  binding:"required,adminpwd" label:"旧密码"
	Password        string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty" binding:"required,adminpwd" label:"新密码"`               //新密码 @gotags:  binding:"required,adminpwd" label:"新密码"
	ConfirmPassword string                 `protobuf:"bytes,3,opt,name=confirmPassword,proto3" json:"confirmPassword,omitempty" binding:"required,adminpwd,eqfield=Password" label:"确认密码"` //确认密码  @gotags: binding:"required,adminpwd,eqfield=Password" label:"确认密码"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReqAccountPasswordEdit) Reset() {
	*x = ReqAccountPasswordEdit{}
	mi := &file_admin_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqAccountPasswordEdit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqAccountPasswordEdit) ProtoMessage() {}

func (x *ReqAccountPasswordEdit) ProtoReflect() protoreflect.Message {
	mi := &file_admin_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqAccountPasswordEdit.ProtoReflect.Descriptor instead.
func (*ReqAccountPasswordEdit) Descriptor() ([]byte, []int) {
	return file_admin_account_proto_rawDescGZIP(), []int{6}
}

func (x *ReqAccountPasswordEdit) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *ReqAccountPasswordEdit) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ReqAccountPasswordEdit) GetConfirmPassword() string {
	if x != nil {
		return x.ConfirmPassword
	}
	return ""
}

type RespAccountPasswordEditData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespAccountPasswordEditData) Reset() {
	*x = RespAccountPasswordEditData{}
	mi := &file_admin_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespAccountPasswordEditData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespAccountPasswordEditData) ProtoMessage() {}

func (x *RespAccountPasswordEditData) ProtoReflect() protoreflect.Message {
	mi := &file_admin_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespAccountPasswordEditData.ProtoReflect.Descriptor instead.
func (*RespAccountPasswordEditData) Descriptor() ([]byte, []int) {
	return file_admin_account_proto_rawDescGZIP(), []int{7}
}

// 个人权限
type ReqAccountPermission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MenuId        int32                  `protobuf:"varint,1,opt,name=menuId,proto3" json:"menuId,omitempty" binding:"required,min=1" label:"菜单ID"` //菜单ID @gotags: binding:"required,min=1" label:"菜单ID"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqAccountPermission) Reset() {
	*x = ReqAccountPermission{}
	mi := &file_admin_account_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqAccountPermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqAccountPermission) ProtoMessage() {}

func (x *ReqAccountPermission) ProtoReflect() protoreflect.Message {
	mi := &file_admin_account_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqAccountPermission.ProtoReflect.Descriptor instead.
func (*ReqAccountPermission) Descriptor() ([]byte, []int) {
	return file_admin_account_proto_rawDescGZIP(), []int{8}
}

func (x *ReqAccountPermission) GetMenuId() int32 {
	if x != nil {
		return x.MenuId
	}
	return 0
}

type RespAccountPermissionData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespAccountPermissionData) Reset() {
	*x = RespAccountPermissionData{}
	mi := &file_admin_account_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespAccountPermissionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespAccountPermissionData) ProtoMessage() {}

func (x *RespAccountPermissionData) ProtoReflect() protoreflect.Message {
	mi := &file_admin_account_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespAccountPermissionData.ProtoReflect.Descriptor instead.
func (*RespAccountPermissionData) Descriptor() ([]byte, []int) {
	return file_admin_account_proto_rawDescGZIP(), []int{9}
}

// 管理员账号详情
type AdminInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AdminId        int32                  `protobuf:"varint,1,opt,name=adminId,proto3" json:"adminId,omitempty"`
	Username       string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Nickname       string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar         string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Email          string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,7,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	LastLoginTime  string                 `protobuf:"bytes,8,opt,name=lastLoginTime,proto3" json:"lastLoginTime,omitempty"`
	LastLoginIp    string                 `protobuf:"bytes,9,opt,name=lastLoginIp,proto3" json:"lastLoginIp,omitempty"`
	LoginTotal     int32                  `protobuf:"varint,10,opt,name=loginTotal,proto3" json:"loginTotal,omitempty"`
	Enabled        bool                   `protobuf:"varint,11,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Token          string                 `protobuf:"bytes,12,opt,name=token,proto3" json:"token,omitempty"`
	Expire         int64                  `protobuf:"varint,13,opt,name=expire,proto3" json:"expire,omitempty"`
	ExpireDataTime string                 `protobuf:"bytes,14,opt,name=expireDataTime,proto3" json:"expireDataTime,omitempty"`
	Menus          map[string]*MenuItem   `protobuf:"bytes,15,rep,name=menus,proto3" json:"menus,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Permissions    map[string]string      `protobuf:"bytes,16,rep,name=permissions,proto3" json:"permissions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Roles          []*AdminUserRoleItem   `protobuf:"bytes,17,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AdminInfo) Reset() {
	*x = AdminInfo{}
	mi := &file_admin_account_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminInfo) ProtoMessage() {}

func (x *AdminInfo) ProtoReflect() protoreflect.Message {
	mi := &file_admin_account_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminInfo.ProtoReflect.Descriptor instead.
func (*AdminInfo) Descriptor() ([]byte, []int) {
	return file_admin_account_proto_rawDescGZIP(), []int{10}
}

func (x *AdminInfo) GetAdminId() int32 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

func (x *AdminInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AdminInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *AdminInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *AdminInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AdminInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AdminInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *AdminInfo) GetLastLoginTime() string {
	if x != nil {
		return x.LastLoginTime
	}
	return ""
}

func (x *AdminInfo) GetLastLoginIp() string {
	if x != nil {
		return x.LastLoginIp
	}
	return ""
}

func (x *AdminInfo) GetLoginTotal() int32 {
	if x != nil {
		return x.LoginTotal
	}
	return 0
}

func (x *AdminInfo) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AdminInfo) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AdminInfo) GetExpire() int64 {
	if x != nil {
		return x.Expire
	}
	return 0
}

func (x *AdminInfo) GetExpireDataTime() string {
	if x != nil {
		return x.ExpireDataTime
	}
	return ""
}

func (x *AdminInfo) GetMenus() map[string]*MenuItem {
	if x != nil {
		return x.Menus
	}
	return nil
}

func (x *AdminInfo) GetPermissions() map[string]string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *AdminInfo) GetRoles() []*AdminUserRoleItem {
	if x != nil {
		return x.Roles
	}
	return nil
}

var File_admin_account_proto protoreflect.FileDescriptor

const file_admin_account_proto_rawDesc = "" +
	"\n" +
	"\x13admin_account.proto\x12\x05admin\x1a\fcommon.proto\x1a\x10admin_menu.proto\"B\n" +
	"\bReqLogin\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"5\n" +
	"\rRespLoginData\x12$\n" +
	"\x04data\x18\x02 \x01(\v2\x10.admin.AdminInfoR\x04data\"4\n" +
	"\x0eReqAccountInfo\x12\"\n" +
	"\frefreshToken\x18\x01 \x01(\bR\frefreshToken\";\n" +
	"\x13RespAccountInfoData\x12$\n" +
	"\x04data\x18\x02 \x01(\v2\x10.admin.AdminInfoR\x04data\"Z\n" +
	"\x0eReqAccountEdit\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x02 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"\x15\n" +
	"\x13RespAccountEditData\"\x80\x01\n" +
	"\x16ReqAccountPasswordEdit\x12 \n" +
	"\voldPassword\x18\x01 \x01(\tR\voldPassword\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12(\n" +
	"\x0fconfirmPassword\x18\x03 \x01(\tR\x0fconfirmPassword\"\x1d\n" +
	"\x1bRespAccountPasswordEditData\".\n" +
	"\x14ReqAccountPermission\x12\x16\n" +
	"\x06menuId\x18\x01 \x01(\x05R\x06menuId\"\x1b\n" +
	"\x19RespAccountPermissionData\"\xd2\x05\n" +
	"\tAdminInfo\x12\x18\n" +
	"\aadminId\x18\x01 \x01(\x05R\aadminId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x1c\n" +
	"\tcreatedAt\x18\x06 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\a \x01(\tR\tupdatedAt\x12$\n" +
	"\rlastLoginTime\x18\b \x01(\tR\rlastLoginTime\x12 \n" +
	"\vlastLoginIp\x18\t \x01(\tR\vlastLoginIp\x12\x1e\n" +
	"\n" +
	"loginTotal\x18\n" +
	" \x01(\x05R\n" +
	"loginTotal\x12\x18\n" +
	"\aenabled\x18\v \x01(\bR\aenabled\x12\x14\n" +
	"\x05token\x18\f \x01(\tR\x05token\x12\x16\n" +
	"\x06expire\x18\r \x01(\x03R\x06expire\x12&\n" +
	"\x0eexpireDataTime\x18\x0e \x01(\tR\x0eexpireDataTime\x121\n" +
	"\x05menus\x18\x0f \x03(\v2\x1b.admin.AdminInfo.MenusEntryR\x05menus\x12C\n" +
	"\vpermissions\x18\x10 \x03(\v2!.admin.AdminInfo.PermissionsEntryR\vpermissions\x12.\n" +
	"\x05roles\x18\x11 \x03(\v2\x18.admin.AdminUserRoleItemR\x05roles\x1aI\n" +
	"\n" +
	"MenusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.admin.MenuItemR\x05value:\x028\x01\x1a>\n" +
	"\x10PermissionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x1bZ\x19./admin_proto;admin_protob\x06proto3"

var (
	file_admin_account_proto_rawDescOnce sync.Once
	file_admin_account_proto_rawDescData []byte
)

func file_admin_account_proto_rawDescGZIP() []byte {
	file_admin_account_proto_rawDescOnce.Do(func() {
		file_admin_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_account_proto_rawDesc), len(file_admin_account_proto_rawDesc)))
	})
	return file_admin_account_proto_rawDescData
}

var file_admin_account_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_admin_account_proto_goTypes = []any{
	(*ReqLogin)(nil),                    // 0: admin.ReqLogin
	(*RespLoginData)(nil),               // 1: admin.RespLoginData
	(*ReqAccountInfo)(nil),              // 2: admin.ReqAccountInfo
	(*RespAccountInfoData)(nil),         // 3: admin.RespAccountInfoData
	(*ReqAccountEdit)(nil),              // 4: admin.ReqAccountEdit
	(*RespAccountEditData)(nil),         // 5: admin.RespAccountEditData
	(*ReqAccountPasswordEdit)(nil),      // 6: admin.ReqAccountPasswordEdit
	(*RespAccountPasswordEditData)(nil), // 7: admin.RespAccountPasswordEditData
	(*ReqAccountPermission)(nil),        // 8: admin.ReqAccountPermission
	(*RespAccountPermissionData)(nil),   // 9: admin.RespAccountPermissionData
	(*AdminInfo)(nil),                   // 10: admin.AdminInfo
	nil,                                 // 11: admin.AdminInfo.MenusEntry
	nil,                                 // 12: admin.AdminInfo.PermissionsEntry
	(*AdminUserRoleItem)(nil),           // 13: admin.AdminUserRoleItem
	(*MenuItem)(nil),                    // 14: admin.MenuItem
}
var file_admin_account_proto_depIdxs = []int32{
	10, // 0: admin.RespLoginData.data:type_name -> admin.AdminInfo
	10, // 1: admin.RespAccountInfoData.data:type_name -> admin.AdminInfo
	11, // 2: admin.AdminInfo.menus:type_name -> admin.AdminInfo.MenusEntry
	12, // 3: admin.AdminInfo.permissions:type_name -> admin.AdminInfo.PermissionsEntry
	13, // 4: admin.AdminInfo.roles:type_name -> admin.AdminUserRoleItem
	14, // 5: admin.AdminInfo.MenusEntry.value:type_name -> admin.MenuItem
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_admin_account_proto_init() }
func file_admin_account_proto_init() {
	if File_admin_account_proto != nil {
		return
	}
	file_common_proto_init()
	file_admin_menu_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_account_proto_rawDesc), len(file_admin_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_admin_account_proto_goTypes,
		DependencyIndexes: file_admin_account_proto_depIdxs,
		MessageInfos:      file_admin_account_proto_msgTypes,
	}.Build()
	File_admin_account_proto = out.File
	file_admin_account_proto_goTypes = nil
	file_admin_account_proto_depIdxs = nil
}
