// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: admin_role.proto

package admin_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoleItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                          //角色ID
	Name            string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                       //角色名称
	RoleName        string `protobuf:"bytes,3,opt,name=roleName,proto3" json:"roleName,omitempty"`               //角色名称
	CreateAdminId   int32  `protobuf:"varint,4,opt,name=createAdminId,proto3" json:"createAdminId,omitempty"`    //创建人ID
	CreateAdminName string `protobuf:"bytes,5,opt,name=createAdminName,proto3" json:"createAdminName,omitempty"` //创建人名称
	Enabled         bool   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`                //是否启用
	CreatedAt       string `protobuf:"bytes,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt       string `protobuf:"bytes,8,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
}

func (x *RoleItem) Reset() {
	*x = RoleItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_role_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleItem) ProtoMessage() {}

func (x *RoleItem) ProtoReflect() protoreflect.Message {
	mi := &file_admin_role_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleItem.ProtoReflect.Descriptor instead.
func (*RoleItem) Descriptor() ([]byte, []int) {
	return file_admin_role_proto_rawDescGZIP(), []int{0}
}

func (x *RoleItem) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleItem) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *RoleItem) GetCreateAdminId() int32 {
	if x != nil {
		return x.CreateAdminId
	}
	return 0
}

func (x *RoleItem) GetCreateAdminName() string {
	if x != nil {
		return x.CreateAdminName
	}
	return ""
}

func (x *RoleItem) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *RoleItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *RoleItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 角色列表
type RoleListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base    *ListBaseReq `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Id      int32        `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`           //角色ID
	Name    string       `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`        //角色名称
	Enabled int32        `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"` //启用状态，0：全部，1：启用，2：禁用
}

func (x *RoleListReq) Reset() {
	*x = RoleListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_role_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleListReq) ProtoMessage() {}

func (x *RoleListReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_role_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleListReq.ProtoReflect.Descriptor instead.
func (*RoleListReq) Descriptor() ([]byte, []int) {
	return file_admin_role_proto_rawDescGZIP(), []int{1}
}

func (x *RoleListReq) GetBase() *ListBaseReq {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *RoleListReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleListReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleListReq) GetEnabled() int32 {
	if x != nil {
		return x.Enabled
	}
	return 0
}

type RoleListRespData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64       `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List  []*RoleItem `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *RoleListRespData) Reset() {
	*x = RoleListRespData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_role_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleListRespData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleListRespData) ProtoMessage() {}

func (x *RoleListRespData) ProtoReflect() protoreflect.Message {
	mi := &file_admin_role_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleListRespData.ProtoReflect.Descriptor instead.
func (*RoleListRespData) Descriptor() ([]byte, []int) {
	return file_admin_role_proto_rawDescGZIP(), []int{2}
}

func (x *RoleListRespData) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *RoleListRespData) GetList() []*RoleItem {
	if x != nil {
		return x.List
	}
	return nil
}

// 有效角色列表
type RoleAllReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`           //角色ID
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`        //角色名称
	Enabled int32  `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"` //启用状态，0：全部，1：启用，2：禁用
}

func (x *RoleAllReq) Reset() {
	*x = RoleAllReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_role_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleAllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleAllReq) ProtoMessage() {}

func (x *RoleAllReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_role_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleAllReq.ProtoReflect.Descriptor instead.
func (*RoleAllReq) Descriptor() ([]byte, []int) {
	return file_admin_role_proto_rawDescGZIP(), []int{3}
}

func (x *RoleAllReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleAllReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleAllReq) GetEnabled() int32 {
	if x != nil {
		return x.Enabled
	}
	return 0
}

type RoleAllResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RoleAllResp) Reset() {
	*x = RoleAllResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_role_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleAllResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleAllResp) ProtoMessage() {}

func (x *RoleAllResp) ProtoReflect() protoreflect.Message {
	mi := &file_admin_role_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleAllResp.ProtoReflect.Descriptor instead.
func (*RoleAllResp) Descriptor() ([]byte, []int) {
	return file_admin_role_proto_rawDescGZIP(), []int{4}
}

// 创建角色
type RoleAddReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`         //角色名称
	Describe string `protobuf:"bytes,2,opt,name=describe,proto3" json:"describe,omitempty"` //角色描述
	Enabled  bool   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`  //启用状态
}

func (x *RoleAddReq) Reset() {
	*x = RoleAddReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_role_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleAddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleAddReq) ProtoMessage() {}

func (x *RoleAddReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_role_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleAddReq.ProtoReflect.Descriptor instead.
func (*RoleAddReq) Descriptor() ([]byte, []int) {
	return file_admin_role_proto_rawDescGZIP(), []int{5}
}

func (x *RoleAddReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleAddReq) GetDescribe() string {
	if x != nil {
		return x.Describe
	}
	return ""
}

func (x *RoleAddReq) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type RoleAddResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RoleAddResp) Reset() {
	*x = RoleAddResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_role_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleAddResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleAddResp) ProtoMessage() {}

func (x *RoleAddResp) ProtoReflect() protoreflect.Message {
	mi := &file_admin_role_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleAddResp.ProtoReflect.Descriptor instead.
func (*RoleAddResp) Descriptor() ([]byte, []int) {
	return file_admin_role_proto_rawDescGZIP(), []int{6}
}

// 角色详情
type RoleInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //角色ID
}

func (x *RoleInfoReq) Reset() {
	*x = RoleInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_role_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleInfoReq) ProtoMessage() {}

func (x *RoleInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_role_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleInfoReq.ProtoReflect.Descriptor instead.
func (*RoleInfoReq) Descriptor() ([]byte, []int) {
	return file_admin_role_proto_rawDescGZIP(), []int{7}
}

func (x *RoleInfoReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RoleInfoRespData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                          //角色ID
	Name            string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                       //角色名称
	Describe        string `protobuf:"bytes,3,opt,name=describe,proto3" json:"describe,omitempty"`               //角色描述
	Enabled         bool   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`                //启用状态
	CreateAdminId   int32  `protobuf:"varint,5,opt,name=createAdminId,proto3" json:"createAdminId,omitempty"`    //创建人ID
	CreateAdminName string `protobuf:"bytes,6,opt,name=createAdminName,proto3" json:"createAdminName,omitempty"` //创建人名称
	ModifyAdminId   int32  `protobuf:"varint,7,opt,name=modifyAdminId,proto3" json:"modifyAdminId,omitempty"`    //修改人ID
	ModifyAdminName string `protobuf:"bytes,8,opt,name=modifyAdminName,proto3" json:"modifyAdminName,omitempty"` //修改人名称
	CreatedAt       string `protobuf:"bytes,9,opt,name=createdAt,proto3" json:"createdAt,omitempty"`             //创建时间
	UpdatedAt       string `protobuf:"bytes,10,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`            //更新时间
}

func (x *RoleInfoRespData) Reset() {
	*x = RoleInfoRespData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_role_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleInfoRespData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleInfoRespData) ProtoMessage() {}

func (x *RoleInfoRespData) ProtoReflect() protoreflect.Message {
	mi := &file_admin_role_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleInfoRespData.ProtoReflect.Descriptor instead.
func (*RoleInfoRespData) Descriptor() ([]byte, []int) {
	return file_admin_role_proto_rawDescGZIP(), []int{8}
}

func (x *RoleInfoRespData) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleInfoRespData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleInfoRespData) GetDescribe() string {
	if x != nil {
		return x.Describe
	}
	return ""
}

func (x *RoleInfoRespData) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *RoleInfoRespData) GetCreateAdminId() int32 {
	if x != nil {
		return x.CreateAdminId
	}
	return 0
}

func (x *RoleInfoRespData) GetCreateAdminName() string {
	if x != nil {
		return x.CreateAdminName
	}
	return ""
}

func (x *RoleInfoRespData) GetModifyAdminId() int32 {
	if x != nil {
		return x.ModifyAdminId
	}
	return 0
}

func (x *RoleInfoRespData) GetModifyAdminName() string {
	if x != nil {
		return x.ModifyAdminName
	}
	return ""
}

func (x *RoleInfoRespData) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *RoleInfoRespData) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 编辑角色
type RoleEditReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`            //角色ID
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`         //角色名称
	Describe string `protobuf:"bytes,3,opt,name=describe,proto3" json:"describe,omitempty"` //角色描述
	Enabled  bool   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`  //启用状态
}

func (x *RoleEditReq) Reset() {
	*x = RoleEditReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_role_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleEditReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleEditReq) ProtoMessage() {}

func (x *RoleEditReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_role_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleEditReq.ProtoReflect.Descriptor instead.
func (*RoleEditReq) Descriptor() ([]byte, []int) {
	return file_admin_role_proto_rawDescGZIP(), []int{9}
}

func (x *RoleEditReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleEditReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleEditReq) GetDescribe() string {
	if x != nil {
		return x.Describe
	}
	return ""
}

func (x *RoleEditReq) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// 启用禁用角色
type RoleEnableReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`           //角色ID
	Enabled bool  `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"` //启用状态
}

func (x *RoleEnableReq) Reset() {
	*x = RoleEnableReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_role_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleEnableReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleEnableReq) ProtoMessage() {}

func (x *RoleEnableReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_role_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleEnableReq.ProtoReflect.Descriptor instead.
func (*RoleEnableReq) Descriptor() ([]byte, []int) {
	return file_admin_role_proto_rawDescGZIP(), []int{10}
}

func (x *RoleEnableReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleEnableReq) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// 删除角色
type RoleDeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                              //角色ID
	PermissionIds []int32 `protobuf:"varint,2,rep,packed,name=permissionIds,proto3" json:"permissionIds,omitempty"` //权限ID集合
}

func (x *RoleDeleteReq) Reset() {
	*x = RoleDeleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_role_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleDeleteReq) ProtoMessage() {}

func (x *RoleDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_role_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleDeleteReq.ProtoReflect.Descriptor instead.
func (*RoleDeleteReq) Descriptor() ([]byte, []int) {
	return file_admin_role_proto_rawDescGZIP(), []int{11}
}

func (x *RoleDeleteReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleDeleteReq) GetPermissionIds() []int32 {
	if x != nil {
		return x.PermissionIds
	}
	return nil
}

// 角色绑定权限
type RoleBindPermissionsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                              //角色ID
	PermissionIds []int32 `protobuf:"varint,2,rep,packed,name=permissionIds,proto3" json:"permissionIds,omitempty"` //权限ID集合
}

func (x *RoleBindPermissionsReq) Reset() {
	*x = RoleBindPermissionsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_role_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleBindPermissionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleBindPermissionsReq) ProtoMessage() {}

func (x *RoleBindPermissionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_role_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleBindPermissionsReq.ProtoReflect.Descriptor instead.
func (*RoleBindPermissionsReq) Descriptor() ([]byte, []int) {
	return file_admin_role_proto_rawDescGZIP(), []int{12}
}

func (x *RoleBindPermissionsReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleBindPermissionsReq) GetPermissionIds() []int32 {
	if x != nil {
		return x.PermissionIds
	}
	return nil
}

type RolePermissionItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId             int32  `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"`                        //权限ID
	PermissionId       int32  `protobuf:"varint,2,opt,name=permissionId,proto3" json:"permissionId,omitempty"`            //权限ID
	PermissionName     string `protobuf:"bytes,3,opt,name=permissionName,proto3" json:"permissionName,omitempty"`         //权限名称
	PermissionKey      string `protobuf:"bytes,4,opt,name=permissionKey,proto3" json:"permissionKey,omitempty"`           //权限键名
	PermissionType     string `protobuf:"bytes,5,opt,name=permissionType,proto3" json:"permissionType,omitempty"`         //权限类型
	PermissionTypeText string `protobuf:"bytes,6,opt,name=permissionTypeText,proto3" json:"permissionTypeText,omitempty"` //权限类型
}

func (x *RolePermissionItem) Reset() {
	*x = RolePermissionItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_role_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RolePermissionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePermissionItem) ProtoMessage() {}

func (x *RolePermissionItem) ProtoReflect() protoreflect.Message {
	mi := &file_admin_role_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePermissionItem.ProtoReflect.Descriptor instead.
func (*RolePermissionItem) Descriptor() ([]byte, []int) {
	return file_admin_role_proto_rawDescGZIP(), []int{13}
}

func (x *RolePermissionItem) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *RolePermissionItem) GetPermissionId() int32 {
	if x != nil {
		return x.PermissionId
	}
	return 0
}

func (x *RolePermissionItem) GetPermissionName() string {
	if x != nil {
		return x.PermissionName
	}
	return ""
}

func (x *RolePermissionItem) GetPermissionKey() string {
	if x != nil {
		return x.PermissionKey
	}
	return ""
}

func (x *RolePermissionItem) GetPermissionType() string {
	if x != nil {
		return x.PermissionType
	}
	return ""
}

func (x *RolePermissionItem) GetPermissionTypeText() string {
	if x != nil {
		return x.PermissionTypeText
	}
	return ""
}

// 角色权限列表
type RolePermissionsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //角色ID
}

func (x *RolePermissionsReq) Reset() {
	*x = RolePermissionsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_role_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RolePermissionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePermissionsReq) ProtoMessage() {}

func (x *RolePermissionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_role_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePermissionsReq.ProtoReflect.Descriptor instead.
func (*RolePermissionsReq) Descriptor() ([]byte, []int) {
	return file_admin_role_proto_rawDescGZIP(), []int{14}
}

func (x *RolePermissionsReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_admin_role_proto protoreflect.FileDescriptor

var file_admin_role_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf0, 0x01, 0x0a, 0x08, 0x52, 0x6f, 0x6c, 0x65,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x6c, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x73, 0x0a, 0x0b, 0x52, 0x6f,
	0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x26, 0x0a, 0x04, 0x62, 0x61, 0x73,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x52, 0x04, 0x62, 0x61, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x22,
	0x4d, 0x0a, 0x10, 0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x23, 0x0a, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e,
	0x52, 0x6f, 0x6c, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x4a,
	0x0a, 0x0a, 0x52, 0x6f, 0x6c, 0x65, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x22, 0x0d, 0x0a, 0x0b, 0x52, 0x6f,
	0x6c, 0x65, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x22, 0x56, 0x0a, 0x0a, 0x52, 0x6f, 0x6c,
	0x65, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c,
	0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65,
	0x64, 0x22, 0x0d, 0x0a, 0x0b, 0x52, 0x6f, 0x6c, 0x65, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x1d, 0x0a, 0x0b, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22,
	0xc8, 0x02, 0x0a, 0x10, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x24,
	0x0a, 0x0d, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x49, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x24,
	0x0a, 0x0d, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x49, 0x64, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6d,
	0x6f, 0x64, 0x69, 0x66, 0x79, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x67, 0x0a, 0x0b, 0x52, 0x6f,
	0x6c, 0x65, 0x45, 0x64, 0x69, 0x74, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x64, 0x22, 0x39, 0x0a, 0x0d, 0x52, 0x6f, 0x6c, 0x65, 0x45, 0x6e, 0x61, 0x62, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x22, 0x45,
	0x0a, 0x0d, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x24, 0x0a, 0x0d, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0d, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x73, 0x22, 0x4e, 0x0a, 0x16, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x69, 0x6e,
	0x64, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x24, 0x0a, 0x0d, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0d, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x73, 0x22, 0xf6, 0x01, 0x0a, 0x12, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x6f,
	0x6c, 0x65, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x70, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x70, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x24, 0x0a, 0x0d, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4b, 0x65,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x12, 0x26, 0x0a, 0x0e, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2e,
	0x0a, 0x12, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x54, 0x65, 0x78, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x70, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x54, 0x65, 0x78, 0x74, 0x22, 0x24,
	0x0a, 0x12, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x42, 0x1b, 0x5a, 0x19, 0x2e, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_admin_role_proto_rawDescOnce sync.Once
	file_admin_role_proto_rawDescData = file_admin_role_proto_rawDesc
)

func file_admin_role_proto_rawDescGZIP() []byte {
	file_admin_role_proto_rawDescOnce.Do(func() {
		file_admin_role_proto_rawDescData = protoimpl.X.CompressGZIP(file_admin_role_proto_rawDescData)
	})
	return file_admin_role_proto_rawDescData
}

var file_admin_role_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_admin_role_proto_goTypes = []any{
	(*RoleItem)(nil),               // 0: admin.RoleItem
	(*RoleListReq)(nil),            // 1: admin.RoleListReq
	(*RoleListRespData)(nil),       // 2: admin.RoleListRespData
	(*RoleAllReq)(nil),             // 3: admin.RoleAllReq
	(*RoleAllResp)(nil),            // 4: admin.RoleAllResp
	(*RoleAddReq)(nil),             // 5: admin.RoleAddReq
	(*RoleAddResp)(nil),            // 6: admin.RoleAddResp
	(*RoleInfoReq)(nil),            // 7: admin.RoleInfoReq
	(*RoleInfoRespData)(nil),       // 8: admin.RoleInfoRespData
	(*RoleEditReq)(nil),            // 9: admin.RoleEditReq
	(*RoleEnableReq)(nil),          // 10: admin.RoleEnableReq
	(*RoleDeleteReq)(nil),          // 11: admin.RoleDeleteReq
	(*RoleBindPermissionsReq)(nil), // 12: admin.RoleBindPermissionsReq
	(*RolePermissionItem)(nil),     // 13: admin.RolePermissionItem
	(*RolePermissionsReq)(nil),     // 14: admin.RolePermissionsReq
	(*ListBaseReq)(nil),            // 15: admin.ListBaseReq
}
var file_admin_role_proto_depIdxs = []int32{
	15, // 0: admin.RoleListReq.base:type_name -> admin.ListBaseReq
	0,  // 1: admin.RoleListRespData.list:type_name -> admin.RoleItem
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_admin_role_proto_init() }
func file_admin_role_proto_init() {
	if File_admin_role_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_admin_role_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*RoleItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_role_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*RoleListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_role_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*RoleListRespData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_role_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*RoleAllReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_role_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*RoleAllResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_role_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*RoleAddReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_role_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*RoleAddResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_role_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*RoleInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_role_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*RoleInfoRespData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_role_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*RoleEditReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_role_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*RoleEnableReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_role_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*RoleDeleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_role_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*RoleBindPermissionsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_role_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*RolePermissionItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_role_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*RolePermissionsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_admin_role_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_admin_role_proto_goTypes,
		DependencyIndexes: file_admin_role_proto_depIdxs,
		MessageInfos:      file_admin_role_proto_msgTypes,
	}.Build()
	File_admin_role_proto = out.File
	file_admin_role_proto_rawDesc = nil
	file_admin_role_proto_goTypes = nil
	file_admin_role_proto_depIdxs = nil
}
