// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: admin_upload.proto

package admin_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 上传记录列表
type ReqAdminUploadList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *ReqListBase           `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	UploadGroup   string                 `protobuf:"bytes,2,opt,name=uploadGroup,proto3" json:"uploadGroup,omitempty"`   //分组（上传路径前缀）
	OriginalName  string                 `protobuf:"bytes,3,opt,name=originalName,proto3" json:"originalName,omitempty"` //原始文件名
	Ext           string                 `protobuf:"bytes,4,opt,name=ext,proto3" json:"ext,omitempty"`                   //扩展名
	Driver        string                 `protobuf:"bytes,5,opt,name=driver,proto3" json:"driver,omitempty"`             //存储驱动
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqAdminUploadList) Reset() {
	*x = ReqAdminUploadList{}
	mi := &file_admin_upload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqAdminUploadList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqAdminUploadList) ProtoMessage() {}

func (x *ReqAdminUploadList) ProtoReflect() protoreflect.Message {
	mi := &file_admin_upload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqAdminUploadList.ProtoReflect.Descriptor instead.
func (*ReqAdminUploadList) Descriptor() ([]byte, []int) {
	return file_admin_upload_proto_rawDescGZIP(), []int{0}
}

func (x *ReqAdminUploadList) GetBase() *ReqListBase {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ReqAdminUploadList) GetUploadGroup() string {
	if x != nil {
		return x.UploadGroup
	}
	return ""
}

func (x *ReqAdminUploadList) GetOriginalName() string {
	if x != nil {
		return x.OriginalName
	}
	return ""
}

func (x *ReqAdminUploadList) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *ReqAdminUploadList) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

type RespAdminUploadListData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*AdminUploadItem     `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespAdminUploadListData) Reset() {
	*x = RespAdminUploadListData{}
	mi := &file_admin_upload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespAdminUploadListData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespAdminUploadListData) ProtoMessage() {}

func (x *RespAdminUploadListData) ProtoReflect() protoreflect.Message {
	mi := &file_admin_upload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespAdminUploadListData.ProtoReflect.Descriptor instead.
func (*RespAdminUploadListData) Descriptor() ([]byte, []int) {
	return file_admin_upload_proto_rawDescGZIP(), []int{1}
}

func (x *RespAdminUploadListData) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *RespAdminUploadListData) GetList() []*AdminUploadItem {
	if x != nil {
		return x.List
	}
	return nil
}

// 上传记录列表请求参数（与前端保持一致：分页参数平铺传递）
type ReqFrontAdminUploadList struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PageSize        int32                  `protobuf:"varint,1,opt,name=pageSize,proto3" json:"pageSize,omitempty"`               // 每页条数
	PageNum         int32                  `protobuf:"varint,2,opt,name=pageNum,proto3" json:"pageNum,omitempty"`                 // 页码
	CreateStartTime int64                  `protobuf:"varint,3,opt,name=createStartTime,proto3" json:"createStartTime,omitempty"` // 查询开始时间戳秒
	CreateEndTime   int64                  `protobuf:"varint,4,opt,name=createEndTime,proto3" json:"createEndTime,omitempty"`     // 查询结束时间戳秒
	UploadGroup     string                 `protobuf:"bytes,5,opt,name=uploadGroup,proto3" json:"uploadGroup,omitempty"`          // 分组（上传路径前缀）
	OriginalName    string                 `protobuf:"bytes,6,opt,name=originalName,proto3" json:"originalName,omitempty"`        // 原始文件名
	Ext             string                 `protobuf:"bytes,7,opt,name=ext,proto3" json:"ext,omitempty"`                          // 扩展名
	Driver          string                 `protobuf:"bytes,8,opt,name=driver,proto3" json:"driver,omitempty"`                    // 存储驱动
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReqFrontAdminUploadList) Reset() {
	*x = ReqFrontAdminUploadList{}
	mi := &file_admin_upload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqFrontAdminUploadList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqFrontAdminUploadList) ProtoMessage() {}

func (x *ReqFrontAdminUploadList) ProtoReflect() protoreflect.Message {
	mi := &file_admin_upload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqFrontAdminUploadList.ProtoReflect.Descriptor instead.
func (*ReqFrontAdminUploadList) Descriptor() ([]byte, []int) {
	return file_admin_upload_proto_rawDescGZIP(), []int{2}
}

func (x *ReqFrontAdminUploadList) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ReqFrontAdminUploadList) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *ReqFrontAdminUploadList) GetCreateStartTime() int64 {
	if x != nil {
		return x.CreateStartTime
	}
	return 0
}

func (x *ReqFrontAdminUploadList) GetCreateEndTime() int64 {
	if x != nil {
		return x.CreateEndTime
	}
	return 0
}

func (x *ReqFrontAdminUploadList) GetUploadGroup() string {
	if x != nil {
		return x.UploadGroup
	}
	return ""
}

func (x *ReqFrontAdminUploadList) GetOriginalName() string {
	if x != nil {
		return x.OriginalName
	}
	return ""
}

func (x *ReqFrontAdminUploadList) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *ReqFrontAdminUploadList) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

// 上传记录列表返回（与前端保持一致：list + pageInfo）
type RespFrontAdminUploadListData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*AdminUploadItem     `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	PageInfo      *PageInfo              `protobuf:"bytes,2,opt,name=pageInfo,proto3" json:"pageInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespFrontAdminUploadListData) Reset() {
	*x = RespFrontAdminUploadListData{}
	mi := &file_admin_upload_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespFrontAdminUploadListData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespFrontAdminUploadListData) ProtoMessage() {}

func (x *RespFrontAdminUploadListData) ProtoReflect() protoreflect.Message {
	mi := &file_admin_upload_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespFrontAdminUploadListData.ProtoReflect.Descriptor instead.
func (*RespFrontAdminUploadListData) Descriptor() ([]byte, []int) {
	return file_admin_upload_proto_rawDescGZIP(), []int{3}
}

func (x *RespFrontAdminUploadListData) GetList() []*AdminUploadItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *RespFrontAdminUploadListData) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

// 上传文件（multipart/form-data：文件字段 file，分组字段 uploadGroup）
type ReqAdminUploadFile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分组即上传路径前缀，如 /admin/user/ ；必须以 / 开头与结尾
	UploadGroup   string `protobuf:"bytes,1,opt,name=uploadGroup,proto3" json:"uploadGroup,omitempty" label:"分组" binding:"required,trimBlank"` // @gotags:  label:"分组" binding:"required,trimBlank"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqAdminUploadFile) Reset() {
	*x = ReqAdminUploadFile{}
	mi := &file_admin_upload_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqAdminUploadFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqAdminUploadFile) ProtoMessage() {}

func (x *ReqAdminUploadFile) ProtoReflect() protoreflect.Message {
	mi := &file_admin_upload_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqAdminUploadFile.ProtoReflect.Descriptor instead.
func (*ReqAdminUploadFile) Descriptor() ([]byte, []int) {
	return file_admin_upload_proto_rawDescGZIP(), []int{4}
}

func (x *ReqAdminUploadFile) GetUploadGroup() string {
	if x != nil {
		return x.UploadGroup
	}
	return ""
}

type RespAdminUploadFileData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *AdminUploadItem       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespAdminUploadFileData) Reset() {
	*x = RespAdminUploadFileData{}
	mi := &file_admin_upload_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespAdminUploadFileData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespAdminUploadFileData) ProtoMessage() {}

func (x *RespAdminUploadFileData) ProtoReflect() protoreflect.Message {
	mi := &file_admin_upload_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespAdminUploadFileData.ProtoReflect.Descriptor instead.
func (*RespAdminUploadFileData) Descriptor() ([]byte, []int) {
	return file_admin_upload_proto_rawDescGZIP(), []int{5}
}

func (x *RespAdminUploadFileData) GetData() *AdminUploadItem {
	if x != nil {
		return x.Data
	}
	return nil
}

// 删除上传记录（同时删除存储上的文件）
type ReqAdminUploadDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" label:"上传记录ID" binding:"required,min=1"` // @gotags:  label:"上传记录ID" binding:"required,min=1"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqAdminUploadDelete) Reset() {
	*x = ReqAdminUploadDelete{}
	mi := &file_admin_upload_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqAdminUploadDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqAdminUploadDelete) ProtoMessage() {}

func (x *ReqAdminUploadDelete) ProtoReflect() protoreflect.Message {
	mi := &file_admin_upload_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqAdminUploadDelete.ProtoReflect.Descriptor instead.
func (*ReqAdminUploadDelete) Descriptor() ([]byte, []int) {
	return file_admin_upload_proto_rawDescGZIP(), []int{6}
}

func (x *ReqAdminUploadDelete) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RespAdminUploadDeleteData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespAdminUploadDeleteData) Reset() {
	*x = RespAdminUploadDeleteData{}
	mi := &file_admin_upload_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespAdminUploadDeleteData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespAdminUploadDeleteData) ProtoMessage() {}

func (x *RespAdminUploadDeleteData) ProtoReflect() protoreflect.Message {
	mi := &file_admin_upload_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespAdminUploadDeleteData.ProtoReflect.Descriptor instead.
func (*RespAdminUploadDeleteData) Descriptor() ([]byte, []int) {
	return file_admin_upload_proto_rawDescGZIP(), []int{7}
}

// 上传记录
type AdminUploadItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                    //记录ID
	AdminId       int32                  `protobuf:"varint,2,opt,name=adminId,proto3" json:"adminId,omitempty"`          //上传者账号ID
	AdminName     string                 `protobuf:"bytes,3,opt,name=adminName,proto3" json:"adminName,omitempty"`       //上传者账号名
	Driver        string                 `protobuf:"bytes,4,opt,name=driver,proto3" json:"driver,omitempty"`             //存储驱动
	DriverText    string                 `protobuf:"bytes,5,opt,name=driverText,proto3" json:"driverText,omitempty"`     //存储驱动名称
	UploadGroup   string                 `protobuf:"bytes,6,opt,name=uploadGroup,proto3" json:"uploadGroup,omitempty"`   //分组（上传路径前缀）
	ObjectKey     string                 `protobuf:"bytes,7,opt,name=objectKey,proto3" json:"objectKey,omitempty"`       //存储对象键（相对路径）
	Url           string                 `protobuf:"bytes,8,opt,name=url,proto3" json:"url,omitempty"`                   //访问链接
	OriginalName  string                 `protobuf:"bytes,9,opt,name=originalName,proto3" json:"originalName,omitempty"` //原始文件名
	NewName       string                 `protobuf:"bytes,10,opt,name=newName,proto3" json:"newName,omitempty"`          //新文件名
	Ext           string                 `protobuf:"bytes,11,opt,name=ext,proto3" json:"ext,omitempty"`                  //扩展名
	Mime          string                 `protobuf:"bytes,12,opt,name=mime,proto3" json:"mime,omitempty"`                //文件类型
	Size          int64                  `protobuf:"varint,13,opt,name=size,proto3" json:"size,omitempty"`               //文件大小（字节）
	SizeText      string                 `protobuf:"bytes,14,opt,name=sizeText,proto3" json:"sizeText,omitempty"`        //文件大小（可读）
	Md5           string                 `protobuf:"bytes,15,opt,name=md5,proto3" json:"md5,omitempty"`                  //文件MD5
	UploadDate    string                 `protobuf:"bytes,16,opt,name=uploadDate,proto3" json:"uploadDate,omitempty"`    //上传日期
	CreatedAt     string                 `protobuf:"bytes,17,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,18,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUploadItem) Reset() {
	*x = AdminUploadItem{}
	mi := &file_admin_upload_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUploadItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUploadItem) ProtoMessage() {}

func (x *AdminUploadItem) ProtoReflect() protoreflect.Message {
	mi := &file_admin_upload_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUploadItem.ProtoReflect.Descriptor instead.
func (*AdminUploadItem) Descriptor() ([]byte, []int) {
	return file_admin_upload_proto_rawDescGZIP(), []int{8}
}

func (x *AdminUploadItem) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminUploadItem) GetAdminId() int32 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

func (x *AdminUploadItem) GetAdminName() string {
	if x != nil {
		return x.AdminName
	}
	return ""
}

func (x *AdminUploadItem) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *AdminUploadItem) GetDriverText() string {
	if x != nil {
		return x.DriverText
	}
	return ""
}

func (x *AdminUploadItem) GetUploadGroup() string {
	if x != nil {
		return x.UploadGroup
	}
	return ""
}

func (x *AdminUploadItem) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *AdminUploadItem) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AdminUploadItem) GetOriginalName() string {
	if x != nil {
		return x.OriginalName
	}
	return ""
}

func (x *AdminUploadItem) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

func (x *AdminUploadItem) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *AdminUploadItem) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *AdminUploadItem) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *AdminUploadItem) GetSizeText() string {
	if x != nil {
		return x.SizeText
	}
	return ""
}

func (x *AdminUploadItem) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *AdminUploadItem) GetUploadDate() string {
	if x != nil {
		return x.UploadDate
	}
	return ""
}

func (x *AdminUploadItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AdminUploadItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_admin_upload_proto protoreflect.FileDescriptor

const file_admin_upload_proto_rawDesc = "" +
	"\n" +
	"\x12admin_upload.proto\x12\x05admin\x1a\fcommon.proto\"\xac\x01\n" +
	"\x12ReqAdminUploadList\x12&\n" +
	"\x04base\x18\x01 \x01(\v2\x12.admin.ReqListBaseR\x04base\x12 \n" +
	"\vuploadGroup\x18\x02 \x01(\tR\vuploadGroup\x12\"\n" +
	"\foriginalName\x18\x03 \x01(\tR\foriginalName\x12\x10\n" +
	"\x03ext\x18\x04 \x01(\tR\x03ext\x12\x16\n" +
	"\x06driver\x18\x05 \x01(\tR\x06driver\"[\n" +
	"\x17RespAdminUploadListData\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12*\n" +
	"\x04list\x18\x02 \x03(\v2\x16.admin.AdminUploadItemR\x04list\"\x8f\x02\n" +
	"\x17ReqFrontAdminUploadList\x12\x1a\n" +
	"\bpageSize\x18\x01 \x01(\x05R\bpageSize\x12\x18\n" +
	"\apageNum\x18\x02 \x01(\x05R\apageNum\x12(\n" +
	"\x0fcreateStartTime\x18\x03 \x01(\x03R\x0fcreateStartTime\x12$\n" +
	"\rcreateEndTime\x18\x04 \x01(\x03R\rcreateEndTime\x12 \n" +
	"\vuploadGroup\x18\x05 \x01(\tR\vuploadGroup\x12\"\n" +
	"\foriginalName\x18\x06 \x01(\tR\foriginalName\x12\x10\n" +
	"\x03ext\x18\a \x01(\tR\x03ext\x12\x16\n" +
	"\x06driver\x18\b \x01(\tR\x06driver\"w\n" +
	"\x1cRespFrontAdminUploadListData\x12*\n" +
	"\x04list\x18\x01 \x03(\v2\x16.admin.AdminUploadItemR\x04list\x12+\n" +
	"\bpageInfo\x18\x02 \x01(\v2\x0f.admin.PageInfoR\bpageInfo\"6\n" +
	"\x12ReqAdminUploadFile\x12 \n" +
	"\vuploadGroup\x18\x01 \x01(\tR\vuploadGroup\"E\n" +
	"\x17RespAdminUploadFileData\x12*\n" +
	"\x04data\x18\x01 \x01(\v2\x16.admin.AdminUploadItemR\x04data\"&\n" +
	"\x14ReqAdminUploadDelete\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x1b\n" +
	"\x19RespAdminUploadDeleteData\"\xe5\x03\n" +
	"\x0fAdminUploadItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\aadminId\x18\x02 \x01(\x05R\aadminId\x12\x1c\n" +
	"\tadminName\x18\x03 \x01(\tR\tadminName\x12\x16\n" +
	"\x06driver\x18\x04 \x01(\tR\x06driver\x12\x1e\n" +
	"\n" +
	"driverText\x18\x05 \x01(\tR\n" +
	"driverText\x12 \n" +
	"\vuploadGroup\x18\x06 \x01(\tR\vuploadGroup\x12\x1c\n" +
	"\tobjectKey\x18\a \x01(\tR\tobjectKey\x12\x10\n" +
	"\x03url\x18\b \x01(\tR\x03url\x12\"\n" +
	"\foriginalName\x18\t \x01(\tR\foriginalName\x12\x18\n" +
	"\anewName\x18\n" +
	" \x01(\tR\anewName\x12\x10\n" +
	"\x03ext\x18\v \x01(\tR\x03ext\x12\x12\n" +
	"\x04mime\x18\f \x01(\tR\x04mime\x12\x12\n" +
	"\x04size\x18\r \x01(\x03R\x04size\x12\x1a\n" +
	"\bsizeText\x18\x0e \x01(\tR\bsizeText\x12\x10\n" +
	"\x03md5\x18\x0f \x01(\tR\x03md5\x12\x1e\n" +
	"\n" +
	"uploadDate\x18\x10 \x01(\tR\n" +
	"uploadDate\x12\x1c\n" +
	"\tcreatedAt\x18\x11 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x12 \x01(\tR\tupdatedAtB\x1bZ\x19./admin_proto;admin_protob\x06proto3"

var (
	file_admin_upload_proto_rawDescOnce sync.Once
	file_admin_upload_proto_rawDescData []byte
)

func file_admin_upload_proto_rawDescGZIP() []byte {
	file_admin_upload_proto_rawDescOnce.Do(func() {
		file_admin_upload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_upload_proto_rawDesc), len(file_admin_upload_proto_rawDesc)))
	})
	return file_admin_upload_proto_rawDescData
}

var file_admin_upload_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_admin_upload_proto_goTypes = []any{
	(*ReqAdminUploadList)(nil),           // 0: admin.ReqAdminUploadList
	(*RespAdminUploadListData)(nil),      // 1: admin.RespAdminUploadListData
	(*ReqFrontAdminUploadList)(nil),      // 2: admin.ReqFrontAdminUploadList
	(*RespFrontAdminUploadListData)(nil), // 3: admin.RespFrontAdminUploadListData
	(*ReqAdminUploadFile)(nil),           // 4: admin.ReqAdminUploadFile
	(*RespAdminUploadFileData)(nil),      // 5: admin.RespAdminUploadFileData
	(*ReqAdminUploadDelete)(nil),         // 6: admin.ReqAdminUploadDelete
	(*RespAdminUploadDeleteData)(nil),    // 7: admin.RespAdminUploadDeleteData
	(*AdminUploadItem)(nil),              // 8: admin.AdminUploadItem
	(*ReqListBase)(nil),                  // 9: admin.ReqListBase
	(*PageInfo)(nil),                     // 10: admin.PageInfo
}
var file_admin_upload_proto_depIdxs = []int32{
	9,  // 0: admin.ReqAdminUploadList.base:type_name -> admin.ReqListBase
	8,  // 1: admin.RespAdminUploadListData.list:type_name -> admin.AdminUploadItem
	8,  // 2: admin.RespFrontAdminUploadListData.list:type_name -> admin.AdminUploadItem
	10, // 3: admin.RespFrontAdminUploadListData.pageInfo:type_name -> admin.PageInfo
	8,  // 4: admin.RespAdminUploadFileData.data:type_name -> admin.AdminUploadItem
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_admin_upload_proto_init() }
func file_admin_upload_proto_init() {
	if File_admin_upload_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_upload_proto_rawDesc), len(file_admin_upload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_admin_upload_proto_goTypes,
		DependencyIndexes: file_admin_upload_proto_depIdxs,
		MessageInfos:      file_admin_upload_proto_msgTypes,
	}.Build()
	File_admin_upload_proto = out.File
	file_admin_upload_proto_goTypes = nil
	file_admin_upload_proto_depIdxs = nil
}
