// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.21.12
// source: admin_api.proto

package admin_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 接口列表请求参数
type ReqApiList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base *ListBaseReq `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Key  string       `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`   //接口键名
	Name string       `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"` //接口名称
	Path string       `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"` //接口路由
}

func (x *ReqApiList) Reset() {
	*x = ReqApiList{}
	mi := &file_admin_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqApiList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqApiList) ProtoMessage() {}

func (x *ReqApiList) ProtoReflect() protoreflect.Message {
	mi := &file_admin_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqApiList.ProtoReflect.Descriptor instead.
func (*ReqApiList) Descriptor() ([]byte, []int) {
	return file_admin_api_proto_rawDescGZIP(), []int{0}
}

func (x *ReqApiList) GetBase() *ListBaseReq {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ReqApiList) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ReqApiList) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReqApiList) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type RespApiListData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64      `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List  []*ApiItem `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *RespApiListData) Reset() {
	*x = RespApiListData{}
	mi := &file_admin_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespApiListData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespApiListData) ProtoMessage() {}

func (x *RespApiListData) ProtoReflect() protoreflect.Message {
	mi := &file_admin_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespApiListData.ProtoReflect.Descriptor instead.
func (*RespApiListData) Descriptor() ([]byte, []int) {
	return file_admin_api_proto_rawDescGZIP(), []int{1}
}

func (x *RespApiListData) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *RespApiListData) GetList() []*ApiItem {
	if x != nil {
		return x.List
	}
	return nil
}

// 全部接口列表
type ReqApiAll struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqApiAll) Reset() {
	*x = ReqApiAll{}
	mi := &file_admin_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqApiAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqApiAll) ProtoMessage() {}

func (x *ReqApiAll) ProtoReflect() protoreflect.Message {
	mi := &file_admin_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqApiAll.ProtoReflect.Descriptor instead.
func (*ReqApiAll) Descriptor() ([]byte, []int) {
	return file_admin_api_proto_rawDescGZIP(), []int{2}
}

// 创建接口
type ReqApiAdd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path     string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`         //接口路由
	Key      string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`           //接口键名
	Name     string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`         //接口名称
	Describe string `protobuf:"bytes,4,opt,name=describe,proto3" json:"describe,omitempty"` //接口描述
	Enabled  bool   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`  //启用状态
}

func (x *ReqApiAdd) Reset() {
	*x = ReqApiAdd{}
	mi := &file_admin_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqApiAdd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqApiAdd) ProtoMessage() {}

func (x *ReqApiAdd) ProtoReflect() protoreflect.Message {
	mi := &file_admin_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqApiAdd.ProtoReflect.Descriptor instead.
func (*ReqApiAdd) Descriptor() ([]byte, []int) {
	return file_admin_api_proto_rawDescGZIP(), []int{3}
}

func (x *ReqApiAdd) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ReqApiAdd) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ReqApiAdd) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReqApiAdd) GetDescribe() string {
	if x != nil {
		return x.Describe
	}
	return ""
}

func (x *ReqApiAdd) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// 接口详情
type ReqApiInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //接口ID
}

func (x *ReqApiInfo) Reset() {
	*x = ReqApiInfo{}
	mi := &file_admin_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqApiInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqApiInfo) ProtoMessage() {}

func (x *ReqApiInfo) ProtoReflect() protoreflect.Message {
	mi := &file_admin_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqApiInfo.ProtoReflect.Descriptor instead.
func (*ReqApiInfo) Descriptor() ([]byte, []int) {
	return file_admin_api_proto_rawDescGZIP(), []int{4}
}

func (x *ReqApiInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 接口编辑
type ReqApiEdit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`            //接口ID
	Path     string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`         //接口路由
	Key      string `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`           //接口键名
	Name     string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`         //接口名称
	Describe string `protobuf:"bytes,5,opt,name=describe,proto3" json:"describe,omitempty"` //接口描述
	Enabled  bool   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`  //接口状态
}

func (x *ReqApiEdit) Reset() {
	*x = ReqApiEdit{}
	mi := &file_admin_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqApiEdit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqApiEdit) ProtoMessage() {}

func (x *ReqApiEdit) ProtoReflect() protoreflect.Message {
	mi := &file_admin_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqApiEdit.ProtoReflect.Descriptor instead.
func (*ReqApiEdit) Descriptor() ([]byte, []int) {
	return file_admin_api_proto_rawDescGZIP(), []int{5}
}

func (x *ReqApiEdit) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReqApiEdit) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ReqApiEdit) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ReqApiEdit) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReqApiEdit) GetDescribe() string {
	if x != nil {
		return x.Describe
	}
	return ""
}

func (x *ReqApiEdit) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// 接口禁用启用
type ReqApiEnable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`           //接口ID
	Enabled bool  `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"` //接口状态
}

func (x *ReqApiEnable) Reset() {
	*x = ReqApiEnable{}
	mi := &file_admin_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqApiEnable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqApiEnable) ProtoMessage() {}

func (x *ReqApiEnable) ProtoReflect() protoreflect.Message {
	mi := &file_admin_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqApiEnable.ProtoReflect.Descriptor instead.
func (*ReqApiEnable) Descriptor() ([]byte, []int) {
	return file_admin_api_proto_rawDescGZIP(), []int{6}
}

func (x *ReqApiEnable) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReqApiEnable) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// 删除接口
type ReqApiDelete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //接口ID
}

func (x *ReqApiDelete) Reset() {
	*x = ReqApiDelete{}
	mi := &file_admin_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqApiDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqApiDelete) ProtoMessage() {}

func (x *ReqApiDelete) ProtoReflect() protoreflect.Message {
	mi := &file_admin_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqApiDelete.ProtoReflect.Descriptor instead.
func (*ReqApiDelete) Descriptor() ([]byte, []int) {
	return file_admin_api_proto_rawDescGZIP(), []int{7}
}

func (x *ReqApiDelete) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_admin_api_proto protoreflect.FileDescriptor

var file_admin_api_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6e, 0x0a, 0x0a, 0x52, 0x65, 0x71, 0x41, 0x70, 0x69,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42,
	0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x4b, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x41, 0x70,
	0x69, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12,
	0x22, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x41, 0x70, 0x69, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x6c,
	0x69, 0x73, 0x74, 0x22, 0x0b, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x41, 0x70, 0x69, 0x41, 0x6c, 0x6c,
	0x22, 0x7b, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x41, 0x70, 0x69, 0x41, 0x64, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x22, 0x1c, 0x0a,
	0x0a, 0x52, 0x65, 0x71, 0x41, 0x70, 0x69, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x8c, 0x01, 0x0a, 0x0a,
	0x52, 0x65, 0x71, 0x41, 0x70, 0x69, 0x45, 0x64, 0x69, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x22, 0x38, 0x0a, 0x0c, 0x52, 0x65,
	0x71, 0x41, 0x70, 0x69, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e,
	0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x64, 0x22, 0x1e, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x41, 0x70, 0x69, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x42, 0x1b, 0x5a, 0x19, 0x2e, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_admin_api_proto_rawDescOnce sync.Once
	file_admin_api_proto_rawDescData = file_admin_api_proto_rawDesc
)

func file_admin_api_proto_rawDescGZIP() []byte {
	file_admin_api_proto_rawDescOnce.Do(func() {
		file_admin_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_admin_api_proto_rawDescData)
	})
	return file_admin_api_proto_rawDescData
}

var file_admin_api_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_admin_api_proto_goTypes = []any{
	(*ReqApiList)(nil),      // 0: admin.ReqApiList
	(*RespApiListData)(nil), // 1: admin.RespApiListData
	(*ReqApiAll)(nil),       // 2: admin.ReqApiAll
	(*ReqApiAdd)(nil),       // 3: admin.ReqApiAdd
	(*ReqApiInfo)(nil),      // 4: admin.ReqApiInfo
	(*ReqApiEdit)(nil),      // 5: admin.ReqApiEdit
	(*ReqApiEnable)(nil),    // 6: admin.ReqApiEnable
	(*ReqApiDelete)(nil),    // 7: admin.ReqApiDelete
	(*ListBaseReq)(nil),     // 8: admin.ListBaseReq
	(*ApiItem)(nil),         // 9: admin.ApiItem
}
var file_admin_api_proto_depIdxs = []int32{
	8, // 0: admin.ReqApiList.base:type_name -> admin.ListBaseReq
	9, // 1: admin.RespApiListData.list:type_name -> admin.ApiItem
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_admin_api_proto_init() }
func file_admin_api_proto_init() {
	if File_admin_api_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_admin_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_admin_api_proto_goTypes,
		DependencyIndexes: file_admin_api_proto_depIdxs,
		MessageInfos:      file_admin_api_proto_msgTypes,
	}.Build()
	File_admin_api_proto = out.File
	file_admin_api_proto_rawDesc = nil
	file_admin_api_proto_goTypes = nil
	file_admin_api_proto_depIdxs = nil
}
